'use server';

import { z } from 'zod';
import { db } from '../lib/db';
import { auth } from '../auth';
import { revalidatePath } from 'next/cache';

const StrategySchema = z.object({
    weeks: z.number(),
    salary_prom: z.number(),
    age: z.number(),
    has_wife: z.boolean(),
    strategyType: z.enum(['INERCIAL', 'RAMPA', 'TOPADO', 'CUSTOM']),
    investment: z.number(),
    netPension: z.number(),
    roiMonths: z.number()
});

export async function saveStrategyAction(formData: FormData) {
    const session = await auth();

    if (!session?.user?.id) {
        return { success: false, error: "Debes iniciar sesión para guardar." };
    }

    const rawInput = {
        weeks: Number(formData.get('weeks')),
        salary_prom: Number(formData.get('salary_prom')),
        age: Number(formData.get('age')),
        has_wife: formData.get('has_wife') === 'true',
        strategyType: formData.get('strategyType'),
        investment: Number(formData.get('investment')),
        netPension: Number(formData.get('netPension')),
        roiMonths: Number(formData.get('roiMonths')),
    };

    const val = StrategySchema.safeParse(rawInput);

    if (!val.success) {
        return { success: false, error: "Datos inválidos." };
    }

    const data = val.data;

    try {
        // 1. Create Parent Simulation Record
        const sim = await db.simulation.create({
            data: {
                userId: session.user.id,
                name: `Estrategia ${data.strategyType} - ${new Date().toLocaleDateString()}`,
                input: JSON.stringify({
                    weeks: data.weeks,
                    salary_prom: data.salary_prom,
                    age: data.age
                }),
                result: JSON.stringify({
                    netPension: data.netPension,
                    roi: data.roiMonths,
                    investment: data.investment,
                    capped_salary: data.salary_prom
                }),
                integrity_hash: "", // To be generated by DossierBuilder later
                is_forensic: false,
                strategies: {
                    create: {
                        type: data.strategyType,
                        investment: data.investment,
                        netPension: data.netPension,
                        roiMonths: data.roiMonths
                    }
                }
            }
        });

        revalidatePath('/dashboard');
        return { success: true, id: sim.id };

    } catch (error) {
        console.error("Save Error:", error);
        return { success: false, error: "Error al guardar en base de datos." };
    }
}
