-- Enable Row Level Security (RLS) on all tables to secure them from public access via Supabase REST API (PostgREST)
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Client" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Simulation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Strategy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EconomicAnchor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WageHistory" ENABLE ROW LEVEL SECURITY;